name: FINAL UserBot
#لا احلل ابدا نسخ الملف بدون ذكر حقوقي.وساكون خصيمك يوم الدين 
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   

concurrency:
  group: final-userbot
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360 

    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run bot
        run: python main.py

      - name: Clean up and verify
        run: |
          echo "✅ تم الانتهاء من العملية بنجاح"
